//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E658WayPoints
    {
        public int WPID { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string WayPoints { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
