//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E658UserMgt
    {
        public int EUMID { get; set; }
        public string SNo { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserLocation { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> MTCotrollerDutyDate { get; set; }
        public Nullable<System.DateTime> HandOverFromDate { get; set; }
        public Nullable<System.DateTime> HandOverToDate { get; set; }
        public Nullable<int> IsTemHandOverStatus { get; set; }
        public string HandOverPsnSNo { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedIP { get; set; }
        public string CreatedMAC { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
    }
}
