//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E658CreaterDetails
    {
        public int ECDID { get; set; }
        public string SNo { get; set; }
        public Nullable<int> RaisedTypeID { get; set; }
        public string StaffServiceNo { get; set; }
        public string OICServiceNo { get; set; }
        public string CreaterLoc { get; set; }
        public string CreaterDivision { get; set; }
        public Nullable<short> IsE658Create { get; set; }
        public Nullable<int> E658MainType { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedIP { get; set; }
        public string CreatedMAC { get; set; }
        public string UserGERMSLocation { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedMAC { get; set; }
    }
}
