//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpasUser
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string rankid { get; set; }
        public string name { get; set; }
        public byte[] password { get; set; }
        public string KitIssParentUnit { get; set; }
        public string DivisionName { get; set; }
        public string DivisionID { get; set; }
    }
}
