//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETransReqHeader
    {
        public int TAHID { get; set; }
        public string CmpTrnsRefNo { get; set; }
        public string DgeAuthRefNo { get; set; }
        public string ReqSection { get; set; }
        public Nullable<int> ReqCategory { get; set; }
        public Nullable<short> IsAddiDutyReq { get; set; }
        public Nullable<int> ETrnsCreatorDltId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedIP { get; set; }
        public string CreatedMAC { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
