//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETransReqDetail
    {
        public int TRDID { get; set; }
        public Nullable<int> ETrnsHedID { get; set; }
        public string DeptFrom { get; set; }
        public string DeptTo { get; set; }
        public Nullable<System.DateTime> DeptDate { get; set; }
        public string DeptTime { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Purpose { get; set; }
        public string Rout { get; set; }
        public string OMTSvcNo { get; set; }
        public string SLAFRegNo { get; set; }
        public string VehicleChassieNo { get; set; }
        public Nullable<short> IsNightPrkReq { get; set; }
        public string NightPrkLoc { get; set; }
        public string SOGORemarks { get; set; }
        public string HQDGERemarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedIP { get; set; }
        public string CreatedMAC { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
