//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F658RegistryHeader
    {
        public string UnitSerialNo { get; set; }
        public string ChassisNo { get; set; }
        public string Seq { get; set; }
        public string PLocation { get; set; }
        public string ELocation { get; set; }
        public string FLocation { get; set; }
        public string TLocation { get; set; }
        public int IsRR658 { get; set; }
        public Nullable<int> AuthorityType { get; set; }
        public Nullable<int> Behavior { get; set; }
        public string Description { get; set; }
        public string OMTNo { get; set; }
        public string Duty { get; set; }
        public string Section { get; set; }
        public string SeniorPassanger { get; set; }
        public Nullable<int> MyNav { get; set; }
        public Nullable<int> MaxNav { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string PTime { get; set; }
        public string PHrs { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<long> E658CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string Route { get; set; }
        public Nullable<int> status_1 { get; set; }
        public Nullable<int> IsOMtReqFromMT { get; set; }
        public Nullable<int> IsVehicleReqFromMT { get; set; }
        public string SLAFRegNo { get; set; }
        public Nullable<short> IsCombineRun { get; set; }
        public Nullable<int> ParentRunCretID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> E658CreatorDltId { get; set; }
        public string RealToLocation { get; set; }
    }
}
