//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> NoOfDivisions { get; set; }
        public Nullable<int> NoOfPersonnel { get; set; }
        public string Description { get; set; }
        public string DBName { get; set; }
        public string SystemURL { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    }
}
