//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRFlowManagementStatu
    {
        public int Rrfid { get; set; }
        public int RRid { get; set; }
        public int Rsid { get; set; }
        public int UserRoleId { get; set; }
        public string EstablishmentId { get; set; }
        public string DivisionId { get; set; }
        public int Active { get; set; }
        public string SubmitServiceNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public string CreateIP { get; set; }
    }
}
