//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHeader
    {
        public int SeqId { get; set; }
        public string RR { get; set; }
        public string Duty { get; set; }
        public string Discription { get; set; }
        public string Location { get; set; }
        public string Division { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> status { get; set; }
        public string Year { get; set; }
        public Nullable<int> CurrentMonth { get; set; }
        public Nullable<int> NextMonth { get; set; }
    }
}
