//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public string ChassisNo { get; set; }
        public string SlafRegNo { get; set; }
        public string CivilRegNo { get; set; }
        public string InventoryNo { get; set; }
        public int TypeID { get; set; }
        public int MakeID { get; set; }
        public int ModelID { get; set; }
        public string EngineNo { get; set; }
        public string YearOfManufacturer { get; set; }
        public Nullable<System.DateTime> DateOfPurchased { get; set; }
        public int stateOfOwnerShip { get; set; }
        public string LocationID { get; set; }
        public string DivisionID { get; set; }
        public Nullable<int> StartingMileage { get; set; }
        public string StartingHrs { get; set; }
        public Nullable<int> USMileage { get; set; }
        public string USHrs { get; set; }
        public Nullable<int> MiloMeter { get; set; }
        public string HrsMeter { get; set; }
        public Nullable<int> TotalMileage { get; set; }
        public string TotalHrs { get; set; }
        public Nullable<decimal> Fuel { get; set; }
        public Nullable<System.DateTime> DateOfNextService { get; set; }
        public Nullable<int> MileageOfNextService { get; set; }
        public string HoursOfNextService { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<int> SType { get; set; }
        public Nullable<bool> DI { get; set; }
        public Nullable<bool> MNM { get; set; }
        public Nullable<bool> RNR { get; set; }
        public Nullable<int> FinalStatus { get; set; }
        public Nullable<System.DateTime> DIDes { get; set; }
        public string MNMDes { get; set; }
        public string RNRDes { get; set; }
        public string FinalStatusDes { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string AttachedLocationID { get; set; }
        public Nullable<int> InsuaranceType { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> PurchaseValue { get; set; }
    }
}
