//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E658.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_RRFlowStatusManagement
    {
        public int SeqId { get; set; }
        public string RR { get; set; }
        public string Duty { get; set; }
        public string Discription { get; set; }
        public string Location { get; set; }
        public string Division { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> status { get; set; }
        public string Year { get; set; }
        public int Rsid { get; set; }
        public int Active { get; set; }
        public int Rrfid { get; set; }
        public int RRid { get; set; }
        public string SubmitServiceNo { get; set; }
        public int UserRoleId { get; set; }
    }
}
